### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by rumenmitrev**
replace micmac repo with latest fork from 
https://github.com/micmacIGN/micmac
and changes from https://github.com/dronemapper-io/micmac

### CODE REVIEW

**Comment by kikislater** [comment]
Nice ! 
Please remove comments in your Dockerfile
line 64 => 69

**Comment by kikislater** [comment]
@rumenmitrev Could we merge it ? 
I have tested it and it works. You took it from master, why not v1.0beta14 ?

**Comment by rumenmitrev** [comment]
On my side it works also.
Yes. I it is form from master.
And it automatically merge master each day. (probably should disable this)

**Comment by kikislater** [comment]
Ok so you have script or just git to auto commit ?
Should we able to make a windows package like they made in official micmac repository. Idea is to have micmac separated from nodemicmac as well as odm structure ... 
And for windows users we should be able to reproduce a package. May be, we will need to revert to official package instead of using fork and mods ! Any thoughts ?

**Comment by kikislater** [comment]
Ok I will inspect your GHA
I will probably make a fork with your mods and host on OpenDroneMap

**Pull request merged**
